#!/usr/bin/env python
# encoding=utf-8

'''
Author: Xu Ke <r#tuoxie.me>
'''

import base64, sys, hashlib

def ordlong(string):
  decimal = 0
  for i in range(len(string)):
    decimal += ord(string[i])*(256**(len(string)-i-1))
  return decimal

S=u'-*-Your Custome String-*-'
S=S.encode('utf-16')
S=base64.encodestring(S).strip()
S=S.replace('=', '').replace('+', 'Y').replace('/', 'Z')

N=unicode(sys.argv[1], 'utf-8')
N=N.encode('utf-16')
N=base64.encodestring(N).strip()
N=N.replace('=', '').replace('+', 'Y').replace('/', 'Z')

encoder = hashlib.sha1()
encoder.update(S)
encoder.update(N)
P=encoder.hexdigest()
P=base64.encodestring(P).strip()
P=P.replace('=', '').replace('+', 'Y').replace('/', 'Z')

T=ordlong(sys.argv[1]) % 1912
for i in range(99999+T):
    e = hashlib.sha1()
    e.update(P)
    P=e.hexdigest()

for i in range(99999+T):
    e = hashlib.md5()
    e.update(P)
    P=e.hexdigest()

P=base64.encodestring(P).strip()
P=P.replace('=', '').replace('+', 'Y').replace('/', 'Z')


for l in (32, 16, 12, 10, 8, 6):
    p = P[32-l/2: 32+l/2]
    if l < 10:
        l = '0' + str(l)
    print l, 'bytes:', p
